[workspace]
authors = ["Kasper Munch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "munch-group"]
name = "mcp_servers"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mcp = ">=1.15.0,<2"
requests = ">=2.32.5,<3"
json5 = ">=0.12.1,<0.13"
