{% set name = "mcp-rest-utils" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../packages/rest-utils

build:
  number: 0
  noarch: generic
  script:
    - npm install --production
    - npm run build
    - mkdir -p $PREFIX/lib/node_modules/@mcp/rest-utils
    - cp -r build node_modules package.json $PREFIX/lib/node_modules/@mcp/rest-utils/

requirements:
  build:
    - nodejs >=20
  run:
    - nodejs >=20

about:
  home: https://github.com/yourusername/mcp_servers
  license: ISC
  license_file: ../../LICENSE
  summary: 'Shared REST API utilities for MCP servers'
  description: |
    Shared REST utilities package providing common functionality for
    REST API-based MCP servers including HTTP client, tool factory,
    and error handling.
  doc_url: https://github.com/yourusername/mcp_servers
  dev_url: https://github.com/yourusername/mcp_servers

extra:
  recipe-maintainers:
    - yourusername
