name: Build and Upload Conda Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        package: [rest-utils, ensembl-mcp, string-mcp]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.11'
        miniforge-version: latest
        activate-environment: build-env

    - name: Install conda-build and anaconda-client
      shell: bash -l {0}
      run: |
        conda install -y conda-build anaconda-client

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: |
        npm install
        npm run build

    - name: Build conda package - ${{ matrix.package }}
      shell: bash -l {0}
      run: |
        conda build conda-recipes/${{ matrix.package }} --output-folder ./conda-bld

    - name: Upload to Anaconda.org
      shell: bash -l {0}
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda -t $ANACONDA_TOKEN upload --force ./conda-bld/**/*.tar.bz2

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: conda-package-${{ matrix.package }}-${{ matrix.os }}
        path: ./conda-bld/**/*.tar.bz2
        retention-days: 7
